name: firebase_analytics
description:
  Flutter plugin for Google Analytics for Firebase, an app measurement
  solution that provides insight on app usage and user engagement on Android and iOS.
homepage: https://firebase.google.com/docs/analytics
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_analytics/firebase_analytics
version: 9.3.5

false_secrets:
 - example/**

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.5'

dependencies:
  firebase_analytics_platform_interface: ^3.3.4
  firebase_analytics_web: 0.4.0+17
  firebase_core: ^1.10.0
  firebase_core_platform_interface: ^4.5.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.analytics
        pluginClass: FlutterFirebaseAnalyticsPlugin
      ios:
        pluginClass: FLTFirebaseAnalyticsPlugin
      macos:
        pluginClass: FLTFirebaseAnalyticsPlugin
      web:
        default_package: firebase_analytics_web
